### ISSUE TITLE
Publish Dist

### ISSUE THREAD

**Issue by shadowtime2000** [greyskullrocks/eleventy-plugins#1]
I was trying to use the tiny css plugin but it seems the `dist` from the build isn't being published with NPM, causing all `eleventy` builds to fail.

**Comment by Marabyte** [comment]
Hey! Sorry for the delay.

Can you share your .eleventy config? I'm not able to reproduce the issue.

**Comment by shadowtime2000** [comment]
@Marabyte This isn't that type of issue... if you [browse the files of eleventy-plugin-tinycss on unpkg](https://unpkg.com/browse/@greyskullrocks/eleventy-plugin-tinycss@1.3.1/), the `dist` folder which is used in the `main` field isn't being published to NPM.

**Comment by Marabyte** [comment]
Ahh! Right! I had an older version of the plugin cached!

This should be fixed in the latest release. can you give it a go : `npm i @greyskullrocks/eleventy-plugin-tinycss@1.3.2`

**Comment by shadowtime2000** [comment]
Great!
